### PR TITLE
Add Holiday to ManualLevel #18

### PR DESCRIPTION
**Pull request by krmarien**

### CODE REVIEW

**Comment by jimmyd-be** [comment]
@krmarien I will check tomorrow this works. You can already set holiday and breeze inside the timer function. This is the default way the Tendon device works. But I will give it a try and if it works I will also add the breeze feature here.

**Comment by krmarien** [comment]
I you set the Holiday mode through the timer, the "Current Ventilation level" will contain a string like "Timer 50 min Holiday".

Currently the library is not able to parse it because Holiday is not a ManualLevel. Probably the same issue will pop up with Breeze?

**Comment by jimmyd-be** [comment]
Thank for clarification. This is indeed a bug. But maybe we can use the TimerLevel enum for parsing the result. This includes holiday and breeze.

**Comment by jimmyd-be** [comment]
I do nog have time today to change this. Tomorrow morning I will do the necessary and also create a new version of the hass plugin

**Comment by krmarien** [comment]
Maybe TimerLevel and ManualLevel can be merged? (Don’t know the details yet of all levels)

**Comment by jimmyd-be** [comment]
I refactored the code by merging the two enums.

**Pull request closed without merging**
